import type {Artifact,CheckPlan,GateEvaluation,RunManifest} from '../../contracts/src/index.js';
import {redactText} from '../../core/src/evidence/redaction.js';
export interface ReportSource {manifest:RunManifest;plan:CheckPlan|null;artifacts:Artifact[]}
export const safeText=(value:string)=>redactText(value);
export const safeRelativePath=(value:string)=>!value.startsWith('/')&&!value.includes('\\')&&!value.includes(':')&&!value.split('/').some(part=>part==='..'||part==='.'||!part)&&!/[\u0000-\u001f\u007f]/.test(value);
export function buildReportView(source:ReportSource,evaluation:GateEvaluation){
 const {manifest}=source,plan=source.plan??{required_check_ids:[] as string[]};
 const checks=manifest.checks.map(check=>({check_id:check.check_id,status:check.status,result_kind:check.result_kind,required:plan.required_check_ids.includes(check.check_id),expected_test_ids:[...check.expected_test_ids],executed_test_ids:[...check.executed_test_ids],missing_test_ids:check.expected_test_ids.filter(id=>!check.executed_test_ids.includes(id)),executed_tests:check.executed_tests,skipped_tests:check.skipped_tests,flaky_tests:check.flaky_tests,reasons:check.reasons.map(safeText),evidence_refs:[...check.evidence_refs]}));
 const missing=plan.required_check_ids.filter(id=>!checks.some(check=>check.check_id===id));
 const incomplete=checks.filter(check=>['BLOCKED','SKIPPED'].includes(check.status)||check.missing_test_ids.length||check.flaky_tests>0);
 return {schema_version:'0.1' as const,decision:evaluation.decision,verdict:evaluation.verdict,historical_verdict:manifest.verdict,freshness:evaluation.freshness,exit_code:evaluation.exit_code,reasons:evaluation.reasons.map(safeText),task:{id:manifest.task_id,revision:manifest.task_revision},run:manifest.run_id,phase:manifest.phase,code_identity:{repo_id:manifest.repo_id,worktree_id:manifest.worktree_id,base_oid:manifest.base_oid,input_hash:manifest.input_hash,plan_hash:manifest.plan_hash},required_checks_known:source.plan!==null,required_checks:[...plan.required_check_ids],executed_checks:checks.filter(check=>!['BLOCKED','SKIPPED'].includes(check.status)).map(check=>check.check_id),missing_checks:missing,checks,failures:checks.filter(check=>['FAIL','ERROR'].includes(check.status)),incomplete_items:incomplete,coverage_gaps:manifest.coverage_gaps.map(safeText),not_verified:[...(source.plan?[]:['PLAN_UNVERIFIED']),...missing,...incomplete.map(check=>check.check_id),...manifest.coverage_gaps.map(safeText)],tool_versions:{...manifest.tool_versions},environment:{reference:manifest.environment_ref,provenance:manifest.environment_ref?'See authenticated environment evidence':'No environment observation claimed'},artifacts:source.artifacts.filter(a=>a.sensitivity==='regular'&&a.redaction_state!=='UNREDACTED'&&safeRelativePath(a.relative_path)).map(a=>({artifact_id:a.artifact_id,relative_path:a.relative_path,digest:a.digest,size:a.size,check_id:a.check_id,retention:a.retention??null})),next_action:`stackgate gate --run ${manifest.run_id} --json`,reproduction:`stackgate run --plan ${manifest.plan_id} --json`,interpretation:'Not verified != Passed. A successful report command does not override the gate exit code.'};
}
export type ReportView=ReturnType<typeof buildReportView>;
