import {it,expect} from 'vitest';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import type {CheckStep,CheckResult} from '../../../packages/contracts/src/index.js';
import {schedulePlan,type SchedulerTransition} from '../../../packages/core/src/execution/scheduler.js';
import {acquireResources} from '../../../packages/core/src/execution/resource-lock.js';
export const step=(id:string,deps:string[]=[],locks:string[]=[]):CheckStep=>({step_id:id,check_id:id,adapter_id:'command',command_id:id,required:true,depends_on:deps,resource_locks:locks,timeout_ms:1000,expected_artifacts:[],expected_test_ids:[],min_tests:null,parameters:{adapter_id:'command',result_kind:'exit-code'}});
export const result=(s:CheckStep,status:CheckResult['status']='PASS'):CheckResult=>({schema_version:'0.1',run_id:'run_test',step_id:s.step_id,check_id:s.check_id,required:s.required,status,result_kind:'exit-code',exit_code:status==='PASS'?0:1,expected_test_ids:[],executed_test_ids:[],discovered_tests:0,executed_tests:0,skipped_tests:0,flaky_tests:0,reasons:[],evidence_refs:['evidence'],attempt_id:'attempt_test',attempts:[]});
async function fixture(){const root=await fs.mkdtemp(path.join(os.tmpdir(),'stackgate-scheduler-'));const repo=path.join(root,'repo');await fs.mkdir(repo);return {repo,root,lockRoot:path.join(root,'locks'),async close(){await fs.rm(root,{recursive:true});}};}
const delay=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
it('runs A to B/C to D with lexicographic starts and real independent concurrency',async()=>{const f=await fixture();try{const events:SchedulerTransition[]=[],steps=[step('d',['b','c']),step('c',['a']),step('b',['a']),step('a')];let active=0,maximum=0;const outcome=await schedulePlan({steps:steps as [CheckStep,...CheckStep[]],required_check_ids:steps.map(s=>s.check_id) as [string,...string[]]},{run_id:'run_test',repo_root:f.repo,worktree_id:'worktree',platform_id:'platform',owner_token:'owner',lockRoot:f.lockRoot,signal:new AbortController().signal,async execute(s){active++;maximum=Math.max(active,maximum);await delay(s.step_id==='b'?40:10);active--;return result(s);},async onTransition(e){events.push(e);}});expect(outcome.blocked).toEqual([]);expect(outcome.results).toHaveLength(4);expect(maximum).toBe(2);expect(events.filter(e=>e.type==='started').map(e=>e.step_id)).toEqual(['a','b','c','d']);expect(events.map(e=>e.sequence)).toEqual([1,2,3,4,5,6,7,8]);}finally{await f.close();}});
it('failure blocks only dependent branches and cancellation stops new steps',async()=>{const f=await fixture();try{for(const cancel of [false,true]){const controller=new AbortController(),started:string[]=[],steps=[step('a'),step('b',['a']),step('c')];const outcome=await schedulePlan({steps:steps as [CheckStep,...CheckStep[]],required_check_ids:['a','b','c']},{run_id:'run_test',repo_root:f.repo,worktree_id:'worktree',platform_id:'platform',owner_token:'owner',lockRoot:f.lockRoot,concurrency:1,signal:controller.signal,async execute(s){started.push(s.step_id);if(cancel)controller.abort();return result(s,s.step_id==='a'?'FAIL':'PASS');},async onTransition(){}});expect(started).toEqual(cancel?['a']:['a','c']);expect(outcome.blocked.map(e=>e.step.step_id)).toEqual(cancel?['b','c']:['b']);expect(outcome.canceled).toBe(cancel);}}finally{await f.close();}});
it('rejects invalid concurrency and never launches malformed DAGs',async()=>{const f=await fixture();try{for(const concurrency of [0,33,1.5])await expect(schedulePlan({steps:[step('a')],required_check_ids:['a']},{run_id:'run_test',repo_root:f.repo,worktree_id:'worktree',platform_id:'platform',owner_token:'owner',lockRoot:f.lockRoot,concurrency,signal:new AbortController().signal,async execute(){throw Error('must not execute');},async onTransition(){}})).rejects.toThrow();}finally{await f.close();}});
it('serializes shared resources while independent resources progress',async()=>{const f=await fixture();try{let active=0,maximum=0;const steps=[step('a',[],['shared']),step('b',[],['shared']),step('c')];const outcome=await schedulePlan({steps:steps as [CheckStep,...CheckStep[]],required_check_ids:['a','b','c']},{run_id:'run_test',repo_root:f.repo,worktree_id:'worktree',platform_id:'platform',owner_token:'owner',lockRoot:f.lockRoot,signal:new AbortController().signal,async execute(s){if(s.resource_locks.length){active++;maximum=Math.max(maximum,active);}await delay(40);if(s.resource_locks.length)active--;return result(s);},async onTransition(){}});expect(maximum).toBe(1);expect(outcome.blocked).toEqual([]);expect(outcome.results).toHaveLength(3);}finally{await f.close();}},30000);
it('does not invent a second result when finished event persistence fails',async()=>{const f=await fixture();try{const outcome=await schedulePlan({steps:[step('a'),step('b',['a'])],required_check_ids:['a','b']},{run_id:'run_test',repo_root:f.repo,worktree_id:'worktree',platform_id:'platform',owner_token:'owner',lockRoot:f.lockRoot,signal:new AbortController().signal,async execute(s){return result(s);},async onTransition(e){if(e.type==='finished')throw Error('disk failure');}});expect(outcome.results.map(s=>s.check_id)).toEqual(['a']);expect(outcome.blocked.map(s=>s.step.check_id)).toEqual(['b']);expect(outcome.diagnostics).toContainEqual(expect.objectContaining({code:'TOOL_FAILURE'}));}finally{await f.close();}});
it('cancels or times out while another owner holds a resource without removing its lock',async()=>{const f=await fixture();const context={run_id:'run_holder',repo_root:f.repo,worktree_id:'worktree',platform_id:'platform',owner_token:'holder',lockRoot:f.lockRoot};const lease=await acquireResources(['shared'],context);try{for(const cancel of [true,false]){const controller=new AbortController(),timer=cancel?setTimeout(()=>controller.abort(),30):null;const outcome=await schedulePlan({steps:[step('a',[],['shared']),step('b',['a'])],required_check_ids:['a','b']},{...context,run_id:'run_test',owner_token:'second',lockTimeoutMs:20,signal:controller.signal,async execute(){throw Error('must not launch');},async onTransition(){}});if(timer)clearTimeout(timer);expect(outcome.results).toEqual([]);expect(outcome.blocked).toHaveLength(2);expect(outcome.blocked[0]!.code).toBe(cancel?'RUN_CANCELED':'RESOURCE_OWNERSHIP_UNVERIFIED');expect(await acquireResources(['shared'],context)).toBeNull();}}finally{await lease!.release();await f.close();}},30000);
it('excludes another whole run even when its workspace locks differ',async()=>{const f=await fixture();try{let signalStarted!:()=>void,finish!:()=>void;const started=new Promise<void>(resolve=>signalStarted=resolve),untilFinish=new Promise<void>(resolve=>finish=resolve);const options={run_id:'run_test',repo_root:f.repo,worktree_id:'worktree',platform_id:'platform',owner_token:'owner',lockRoot:f.lockRoot,signal:new AbortController().signal,async onTransition(){}};const first=schedulePlan({steps:[step('a',[],['workspace_one'])],required_check_ids:['a']},{...options,async execute(s){signalStarted();await untilFinish;return result(s);}});await started;const second=await schedulePlan({steps:[step('b',[],['workspace_two'])],required_check_ids:['b']},{...options,owner_token:'other',async execute(s){return result(s);}});finish();await first;expect(second.results).toEqual([]);expect(second.blocked[0]?.code).toBe('RESOURCE_OWNERSHIP_UNVERIFIED');}finally{await f.close();}},30000);
it('records queue waiting separately from actual execution duration',async()=>{const f=await fixture();try{const outcome=await schedulePlan({steps:[step('a'),step('b',['a'])],required_check_ids:['a','b']},{run_id:'run_test',repo_root:f.repo,worktree_id:'worktree',platform_id:'platform',owner_token:'owner',lockRoot:f.lockRoot,signal:new AbortController().signal,async execute(s){await delay(25);return result(s);},async onTransition(){}});const timings=(outcome as unknown as {timings:Record<string,{waiting_ms:number;execution_ms:number}>}).timings;expect(timings?.a?.execution_ms).toBeGreaterThanOrEqual(20);expect(timings?.b?.waiting_ms).toBeGreaterThan(timings?.a?.waiting_ms??0);}finally{await f.close();}});
