import {expect,it,vi} from 'vitest';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {taskProject} from '../../support/task-project.js';
import {TrustService} from '../../../packages/core/src/services/trust-service.js';
import { UserTrustStore } from '../../../packages/core/src/storage/user-trust-store.js';
vi.setConfig({testTimeout:120000});
it('does not recognize mismatched grant IDs or permission scopes as trusted',async()=>{const f=await fixture();try{const preview=await f.service.review();const granted=await f.service.confirm(preview.execution_digest,{authorized:true});const record=JSON.parse(await fs.readFile(granted.trust_ref,'utf8'));for(const patch of [{trust_id:'trust_unrelated'},{allowed_command_ids:['other-command']},{allowed_origins:['https://unrelated.example']},{allowed_paths:['other-path']}]){await fs.writeFile(granted.trust_ref,JSON.stringify({...record,...patch}));expect((await f.service.review()).already_trusted).toBe(false);} }finally{await f.close();}});
it('refuses a script whose bytes are excluded by the credential-input policy',async()=>{const f=await fixture();try{await fs.writeFile(path.join(f.root,'apps/api/runner.pem'),'// ordinary script with a credential-like extension');f.config.commands.export_api.args=['runner.pem'];await fs.writeFile(path.join(f.root,'.stackgate.yaml'),JSON.stringify(f.config));await expect(f.service.review()).rejects.toThrow();}finally{await f.close();}});
it('renews an expired matching record and preserves unrelated or concurrently changed records',async()=>{const f=await fixture();try{const preview=await f.service.review();const granted=await f.service.confirm(preview.execution_digest,{authorized:true});const record=JSON.parse(await fs.readFile(granted.trust_ref,'utf8'));record.expires_at='2020-01-01T00:00:00.000Z';await fs.writeFile(granted.trust_ref,JSON.stringify(record));expect((await f.service.review()).already_trusted).toBe(false);await expect(f.service.confirm(preview.execution_digest,{authorized:true})).resolves.toMatchObject({trusted:true});expect((await f.service.review()).already_trusted).toBe(true);const store=new UserTrustStore(f.root,f.store);const entry=await store.readEntry(preview.execution_digest);expect(entry).not.toBeNull();await fs.appendFile(granted.trust_ref,' ');await expect(store.write(entry!.record,entry!)).rejects.toThrow();const unrelated={...record,repo_id:'repo_other'};await fs.writeFile(granted.trust_ref,JSON.stringify(unrelated));await expect(f.service.confirm(preview.execution_digest,{authorized:true})).rejects.toThrow();expect(JSON.parse(await fs.readFile(granted.trust_ref,'utf8')).repo_id).toBe('repo_other');}finally{await f.close();}});
it('rejects external script arguments and binds ignored scripts outside workspaces',async()=>{const f=await fixture();try{const external=path.join(f.store,'external.js');await fs.writeFile(external,'process.exit(0)');f.config.commands.export_api.args=[external];await fs.writeFile(path.join(f.root,'.stackgate.yaml'),JSON.stringify(f.config));await expect(f.service.review()).rejects.toThrow();await fs.writeFile(path.join(f.root,'.gitignore'),'root-script.js\n');await fs.writeFile(path.join(f.root,'root-script.js'),'// reviewed');f.config.commands.export_api.args=['-c','../../root-script.js'];await fs.writeFile(path.join(f.root,'.stackgate.yaml'),JSON.stringify(f.config));const before=await f.service.review();await f.service.confirm(before.execution_digest,{authorized:true});await fs.writeFile(path.join(f.root,'root-script.js'),'// changed');expect((await f.service.review()).already_trusted).toBe(false);await expect(f.service.confirm(before.execution_digest,{authorized:true})).rejects.toThrow();}finally{await f.close();}});
it('binds inline code as arguments without interpreting code fragments as paths',async()=>{const f=await fixture();try{f.config.commands.export_api.args=['--eval','console.log("/outside/script.js")'];await fs.writeFile(path.join(f.root,'.stackgate.yaml'),JSON.stringify(f.config));const before=await f.service.review();expect(before.execution_preview.commands.find(command=>command.id==='export_api')!.args).toEqual(f.config.commands.export_api.args);}finally{await f.close();}});
it('binds resolved tool identity without launching it',async()=>{const f=await fixture();try{const tool=path.join(f.store,'fake.exe');await fs.writeFile(tool,'not executable');const service=new TrustService(f.root,{storeRoot:f.store,additionalTools:{oasdiff:tool}});const before=await service.review();await fs.writeFile(tool,'different executable bytes');expect((await service.review()).execution_digest).not.toBe(before.execution_digest);await expect(service.confirm(before.execution_digest,{authorized:true})).rejects.toThrow();}finally{await f.close();}});
async function fixture(){const repo=await taskProject();const store=await fs.mkdtemp(path.join(os.tmpdir(),'stackgate-trust-'));for(const w of Object.values(repo.config.workspaces) as {path:string}[])await fs.mkdir(path.join(repo.root,w.path),{recursive:true});for(const c of Object.values(repo.config.commands) as {exec:string;args:string[]}[]){c.exec=process.execPath;c.args=['script.js'];}await fs.writeFile(path.join(repo.root,'apps/web/script.js'),'throw new Error("NEVER EXECUTE");');await fs.writeFile(path.join(repo.root,'apps/api/script.js'),'throw new Error("NEVER EXECUTE");');await fs.writeFile(path.join(repo.root,'.stackgate.yaml'),JSON.stringify(repo.config));return {...repo,store,service:new TrustService(repo.root,{storeRoot:store}),async close(){await repo.cleanup();await fs.rm(store,{recursive:true});}};}
it('previews names only and never trusts without explicit reviewed authorization',async()=>{const f=await fixture();try{process.env.STACKGATE_TEST_TOKEN='secret-sentinel';const p=await f.service.review();expect(p.already_trusted).toBe(false);expect(JSON.stringify(p)).not.toContain('secret-sentinel');expect(p.execution_preview.environment_names).toContain('STACKGATE_TEST_TOKEN');expect(p.execution_preview.commands[0]).toMatchObject({executable:process.execPath,args:['script.js']});expect(await fs.readdir(f.store)).toEqual([]);await expect(f.service.confirm(p.execution_digest,{authorized:false})).rejects.toThrow();await expect(f.service.confirm('',{authorized:true})).rejects.toThrow();}finally{delete process.env.STACKGATE_TEST_TOKEN;await f.close();}});
it('stores outside repository, binds scripts, arguments and origins, and does not become CI trust',async()=>{const f=await fixture();try{const p=await f.service.review();const result=await f.service.confirm(p.execution_digest,{authorized:true});expect(result.trusted).toBe(true);expect(result.trust_ref.startsWith(f.store)).toBe(true);expect((await f.service.review()).already_trusted).toBe(true);process.env.CI='true';const record=JSON.parse(await fs.readFile(result.trust_ref,'utf8'));expect(record.trust_source).toBe('local-execution');await fs.appendFile(path.join(f.root,'apps/api/script.js'),'\n// changed');expect((await f.service.review()).already_trusted).toBe(false);await expect(f.service.confirm(p.execution_digest,{authorized:true})).rejects.toThrow();await fs.writeFile(path.join(f.root,'apps/api/new-script.js'),'// new script');f.config.commands.export_api.args=['new-script.js'];f.config.security.allow_origins.push('https://example.test');await fs.writeFile(path.join(f.root,'.stackgate.yaml'),JSON.stringify(f.config));expect((await f.service.review()).execution_digest).not.toBe(p.execution_digest);}finally{delete process.env.CI;await f.close();}});
it('refuses repository-contained trust stores and copying trust into another checkout',async()=>{const a=await fixture(),b=await fixture();try{await expect(new TrustService(a.root,{storeRoot:path.join(a.root,'trust')}).review()).rejects.toThrow();const p=await a.service.review();const saved=await a.service.confirm(p.execution_digest,{authorized:true});await fs.cp(a.store,b.store,{recursive:true});expect((await b.service.review()).already_trusted).toBe(false);const record=JSON.parse(await fs.readFile(saved.trust_ref,'utf8'));expect(record.input_hash).not.toBe((await b.service.review()).execution_digest);}finally{await a.close();await b.close();}});
