import type {CheckPlan,CheckResult,CheckStep,Diagnostic} from '../../../contracts/src/index.js';
import {validateSchema} from '../../../contracts/src/index.js';
import {normalizePlanDag} from '../domain/plan-dag.js';
import {acquireResources,type ResourceLease} from './resource-lock.js';
export interface SchedulerTransition {sequence:number;type:'started'|'finished'|'blocked';step_id:string;check_id:string;status?:CheckResult['status']}
export interface SchedulerOptions {run_id:string;repo_root:string;worktree_id:string;platform_id:string;owner_token:string;signal:AbortSignal;concurrency?:number;lockRoot?:string;lockTimeoutMs?:number;execute(step:CheckStep):Promise<CheckResult>;onTransition(event:SchedulerTransition):Promise<void>}
export interface SchedulerResult {results:CheckResult[];blocked:{step:CheckStep;code:Diagnostic['code'];message:string}[];canceled:boolean;diagnostics:Diagnostic[];timings:Record<string,{queued_at:string;started_at:string|null;finished_at:string|null;waiting_ms:number;execution_ms:number}>}
export async function schedulePlan(plan:Pick<CheckPlan,'steps'|'required_check_ids'>,options:SchedulerOptions):Promise<SchedulerResult>{
 const concurrency=options.concurrency??2;if(!Number.isInteger(concurrency)||concurrency<1||concurrency>32)throw Error('Scheduler concurrency must be an integer from 1 to 32');
 const lockTimeout=options.lockTimeoutMs??30000;if(!Number.isInteger(lockTimeout)||lockTimeout<1||lockTimeout>300000)throw Error('Resource lock timeout must be from 1 to 300000 ms');
 const steps=normalizePlanDag(plan.steps,plan.required_check_ids),pending=new Map(steps.map(step=>[step.step_id,step])),completed=new Map<string,CheckResult['status']>(),running=new Map<string,Promise<void>>();
 const outcome:SchedulerResult={results:[],blocked:[],canceled:false,diagnostics:[],timings:{}};let sequence=0,events=Promise.resolve(),eventFailed=false;
 const queued=performance.now(),executionStarts=new Map<string,number>();for(const step of steps)outcome.timings[step.step_id]={queued_at:new Date().toISOString(),started_at:null,finished_at:null,waiting_ms:0,execution_ms:0};
 const finishTiming=(step:CheckStep)=>{const timing=outcome.timings[step.step_id]!;if(timing.finished_at)return;timing.finished_at=new Date().toISOString();const start=executionStarts.get(step.step_id);if(start===undefined)timing.waiting_ms=performance.now()-queued;else timing.execution_ms=performance.now()-start;};
 const busyResources=new Set<string>(),waitingSince=new Map<string,number>();
 const diagnostic=(message:string):Diagnostic=>({code:'TOOL_FAILURE',message,location:'',source:'scheduler',observed_facts:{},recommended_action:'Review recorded scheduler failure before retrying.'});
 const emit=(type:SchedulerTransition['type'],step:CheckStep,status?:CheckResult['status'])=>{const event:SchedulerTransition={sequence:++sequence,type,step_id:step.step_id,check_id:step.check_id,...(status?{status}:{})};const next=events.then(()=>options.onTransition(event));events=next.catch(error=>{eventFailed=true;outcome.diagnostics.push(diagnostic(error instanceof Error?error.message:'Event persistence failed'));});return next;};
 const block=async(step:CheckStep,code:Diagnostic['code'],message:string)=>{finishTiming(step);pending.delete(step.step_id);completed.set(step.step_id,'BLOCKED');outcome.blocked.push({step,code,message});await emit('blocked',step,'BLOCKED').catch(()=>{});};
 const launch=(step:CheckStep,lease:ResourceLease)=>{pending.delete(step.step_id);for(const resource of step.resource_locks)busyResources.add(resource);const execution=(async()=>{try{if(options.signal.aborted||eventFailed){await block(step,'RUN_CANCELED','Execution canceled before launch');return;}await emit('started',step);if(options.signal.aborted||eventFailed){await block(step,'RUN_CANCELED','Execution canceled before launch');return;}const timing=outcome.timings[step.step_id]!;timing.started_at=new Date().toISOString();timing.waiting_ms=performance.now()-queued;executionStarts.set(step.step_id,performance.now());const result=await options.execute(step);finishTiming(step);if(!validateSchema('check-result',result).ok||result.run_id!==options.run_id||result.step_id!==step.step_id||result.check_id!==step.check_id||result.required!==step.required)throw Error('Executor returned an invalid or mismatched CheckResult');outcome.results.push(result);completed.set(step.step_id,result.status);await emit('finished',step,result.status);}catch(error){if(outcome.results.some(result=>result.step_id===step.step_id)){completed.set(step.step_id,'ERROR');eventFailed=true;}else await block(step,'TOOL_FAILURE',error instanceof Error?error.message:'Step execution failed');}finally{try{await lease.release();}catch(error){completed.set(step.step_id,'ERROR');eventFailed=true;outcome.diagnostics.push({...diagnostic(error instanceof Error?error.message:'Resource release failed'),code:'RESOURCE_OWNERSHIP_UNVERIFIED'});}for(const resource of step.resource_locks)busyResources.delete(resource);running.delete(step.step_id);}})();running.set(step.step_id,execution);};
 let runLease:ResourceLease|null=null;
 try{runLease=await acquireResources(['worktree_execution'],options);}catch(error){outcome.diagnostics.push({...diagnostic(error instanceof Error?error.message:'Worktree ownership unavailable'),code:'RESOURCE_OWNERSHIP_UNVERIFIED'});}
 if(!runLease){for(const step of steps)await block(step,'RESOURCE_OWNERSHIP_UNVERIFIED','Worktree already has an active or unverifiable execution owner');await events;outcome.canceled=options.signal.aborted;return outcome;}
 try{while(pending.size||running.size){
  for(const step of [...pending.values()].sort((a,b)=>a.step_id.localeCompare(b.step_id))){
   if(options.signal.aborted||eventFailed){await block(step,'RUN_CANCELED',eventFailed?'Execution evidence or ownership failed; further execution stopped':'Run canceled');continue;}
   if(step.depends_on.some(id=>!running.has(id)&&completed.has(id)&&completed.get(id)!=='PASS')){await block(step,'DEPENDENCY_BLOCKED','A dependency did not pass');continue;}
   if(running.size<concurrency&&step.depends_on.every(id=>!running.has(id)&&completed.get(id)==='PASS')&&!step.resource_locks.some(resource=>busyResources.has(resource))){
    try{const lease=await acquireResources(step.resource_locks,options);if(lease){waitingSince.delete(step.step_id);launch(step,lease);}else{const since=waitingSince.get(step.step_id)??Date.now();waitingSince.set(step.step_id,since);if(Date.now()-since>=lockTimeout)await block(step,'RESOURCE_OWNERSHIP_UNVERIFIED','Resource remains owned by another or unverifiable process; no lock was reaped');}}catch(error){await block(step,'RESOURCE_OWNERSHIP_UNVERIFIED',error instanceof Error?error.message:'Resource ownership could not be verified');}
   }
  }
  if(running.size)await Promise.race(running.values());else if(pending.size){if(!waitingSince.size)throw Error('Scheduler made no progress');await new Promise<void>(resolve=>{const done=()=>{clearTimeout(timer);options.signal.removeEventListener('abort',done);resolve();};const timer=setTimeout(done,25);options.signal.addEventListener('abort',done,{once:true});});}
 }}finally{await Promise.all(running.values());try{await runLease.release();}catch(error){outcome.diagnostics.push({...diagnostic(error instanceof Error?error.message:'Worktree owner release failed'),code:'RESOURCE_OWNERSHIP_UNVERIFIED'});}}
 await events;outcome.canceled=options.signal.aborted;outcome.results.sort((a,b)=>a.step_id.localeCompare(b.step_id));outcome.blocked.sort((a,b)=>a.step.step_id.localeCompare(b.step.step_id));return outcome;
}
