import { afterEach, describe, expect, it } from 'vitest';
import fs from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { makeRepo, git } from '../../support/git-repo.js';
import { resolveBaseline } from '../../../packages/adapter-git/src/baseline.js';
import { inspectRepository } from '../../../packages/adapter-git/src/repository.js';
const repos: Awaited<ReturnType<typeof makeRepo>>[] = [];
async function repo() { const r = await makeRepo(); repos.push(r); return r; }
afterEach(async () => { await Promise.all(repos.splice(0).map(r => r.cleanup())); });
describe('fixed Git baselines', () => {
  it('pins actual merge base and advancing target with detached HEAD', async () => { const r = await repo(); const base = await r.git('rev-parse', 'HEAD'); await r.git('branch', 'feature'); const tip = await r.commit('target.txt', 'target'); await r.git('checkout', '--detach', 'feature'); const b = await resolveBaseline({project_root:r.root,target_ref:'main'}); expect(b).toMatchObject({base_oid:base,head_oid:base,target_tip_oid:tip,git_object_format:'sha1'}); });
  it('rejects missing refs and option-like refs', async () => { const r = await repo(); await expect(resolveBaseline({project_root:r.root,target_ref:'missing'})).rejects.toMatchObject({code:'BASELINE_MISSING'}); await expect(resolveBaseline({project_root:r.root,target_ref:'--help'})).rejects.toMatchObject({code:'INVALID_REF'}); });
  it('treats leading dash directory as path and hashes local identities', async () => { const r = await repo(); const moved = path.join(r.root, '-repo'); await git(r.root,'worktree','add','--detach',moved); const a = await inspectRepository(r.root), b = await inspectRepository(moved); expect(a.repo_id).toBe(b.repo_id); expect(a.worktree_id).not.toBe(b.worktree_id); expect(a.repo_id).toMatch(/^repo_[a-f0-9]{64}$/); expect(a.worktree_id).toMatch(/^worktree_[a-f0-9]{64}$/); expect(b.repo_root).toBe(await fs.realpath(moved)); });
  it('fails explicitly when shallow history cannot establish a common ancestor', async () => { const r = await repo(); const base = await r.git('rev-parse','HEAD'); await r.commit('next','next'); const clone = path.join(r.root,'shallow'); await git(r.root,'clone','--depth','1',pathToFileURL(r.root).href,clone); await expect(resolveBaseline({project_root:clone,target_ref:base})).rejects.toMatchObject({code:'BASELINE_MISSING'}); });
  it('rejects unresolved merges', async () => { const r = await repo(); await r.git('checkout','-b','other'); await r.commit('source.txt','other'); await r.git('checkout','main'); await r.commit('source.txt','main'); await r.git('merge','other').catch(() => {}); await expect(resolveBaseline({project_root:r.root,target_ref:'main'})).rejects.toMatchObject({code:'UNRESOLVED_MERGE'}); });
  it('disables repository fsmonitor and ignores hostile inherited Git environment', async () => { const r = await repo(); const marker = path.join(r.root,'executed'); await r.git('config','core.fsmonitor',`echo unsafe > '${marker.replaceAll('\\','/')}'`); const previous = process.env.GIT_DIR; process.env.GIT_DIR = path.join(r.root,'missing'); try { await expect(resolveBaseline({project_root:r.root,target_ref:'main'})).resolves.toHaveProperty('head_oid'); } finally { if (previous === undefined) delete process.env.GIT_DIR; else process.env.GIT_DIR = previous; } await expect(fs.stat(marker)).rejects.toMatchObject({code:'ENOENT'}); });
  it('reports nonrepository distinctly', async () => { const r = await repo(); await expect(inspectRepository(path.dirname(r.root))).rejects.toMatchObject({code:'NOT_A_REPOSITORY'}); });
  it('does not choose arbitrarily between multiple merge bases', async () => { const r = await repo(); const base = await r.git('rev-parse','HEAD'); const tree = await r.git('rev-parse','HEAD^{tree}'); const a = await r.git('commit-tree',tree,'-p',base,'-m','a'); const b = await r.git('commit-tree',tree,'-p',base,'-m','b'); const c = await r.git('commit-tree',tree,'-p',a,'-p',b,'-m','c'); const d = await r.git('commit-tree',tree,'-p',b,'-p',a,'-m','d'); await expect(resolveBaseline({project_root:r.root,target_ref:c,head_ref:d})).rejects.toMatchObject({code:'AMBIGUOUS_BASELINE'}); });
});
