import { afterEach, describe, expect, it } from 'vitest';
import fs from 'node:fs/promises';
import path from 'node:path';
import { makeRepo } from '../../support/git-repo.js';
import { resolveBaseline } from '../../../packages/adapter-git/src/baseline.js';
import { captureInputs, type InputScope } from '../../../packages/adapter-git/src/input-manifest.js';
import { hashBytes } from '../../../packages/core/src/storage/hash.js';
import { validateSchema } from '../../../packages/contracts/src/index.js';
const repos: Awaited<ReturnType<typeof makeRepo>>[] = [];
async function setup() { const r = await makeRepo(); repos.push(r); const baseline = await resolveBaseline({project_root:r.root,target_ref:'main'}); return {...r, async capture(scope:InputScope = {}) { return captureInputs({project_id:'test',repo_root:r.root,configuration_hash:'a'.repeat(64),workspaces:{},contracts:{}},baseline,scope); }}; }
afterEach(async () => { await Promise.all(repos.splice(0).map(r => r.cleanup())); });
describe('complete input byte capture', () => {
  it('emits schema-valid SafeIds in a real captured manifest',async()=>{const r=await setup();const manifest=await r.capture();expect(manifest.repo_id).toMatch(/^repo_[a-f0-9]{64}$/);expect(manifest.worktree_id).toMatch(/^worktree_[a-f0-9]{64}$/);expect(validateSchema('input-manifest',manifest).ok).toBe(true);});
  it('hashes final bytes B while keeping staged A and unstaged explanations', async () => { const r = await setup(); await fs.writeFile(path.join(r.root,'source.txt'),'A'); await r.git('add','source.txt'); await fs.writeFile(path.join(r.root,'source.txt'),'B'); const m = await r.capture(); expect(m.files.find(f => f.relative_path === 'source.txt')).toMatchObject({digest:hashBytes(Buffer.from('B')),staged:true,unstaged:true}); expect(m.staged_changes).toContain('source.txt'); expect(m.unstaged_changes).toContain('source.txt'); });
  it('includes untracked source and dependency locks in input hash', async () => { const r = await setup(); const a = await r.capture(); await fs.writeFile(path.join(r.root,'frontend.tsx'),'export const x = 1'); const b = await r.capture(); expect(b.input_hash).not.toBe(a.input_hash); await fs.writeFile(path.join(r.root,'pnpm-lock.yaml'),'lockfileVersion: 9'); const c = await r.capture(); expect(c.input_hash).not.toBe(b.input_hash); expect(c.files.find(f => f.relative_path === 'frontend.tsx')).toMatchObject({tracked:false,kind:'file'}); });
  it('retains tombstones for staged and unstaged deletions', async () => { const r = await setup(); await fs.unlink(path.join(r.root,'source.txt')); const a = await r.capture(); expect(a.files[0]).toMatchObject({kind:'deleted',digest:null,unstaged:true}); await r.git('add','-u'); const b = await r.capture(); expect(b.files[0]).toMatchObject({kind:'deleted',staged:true}); });
  it('explicitly includes ignored build inputs and diagnoses missing required inputs', async () => { const r = await setup(); await fs.writeFile(path.join(r.root,'.gitignore'),'generated/\n'); await fs.mkdir(path.join(r.root,'generated')); await fs.writeFile(path.join(r.root,'generated','config.json'),'{}'); expect((await r.capture()).files.some(f => f.relative_path.startsWith('generated/'))).toBe(false); expect((await r.capture({include_ignored:['generated']})).files.some(f => f.relative_path === 'generated/config.json')).toBe(true); expect((await r.capture({include_ignored:['missing']})).completeness).toBe('UNKNOWN'); });
  it('excludes declared outputs and credential files with reasons', async () => { const r = await setup(); const scope = {exclusions:[{relative_path:'dist',reason:'declared build output'}]}; const a = await r.capture(scope); await fs.mkdir(path.join(r.root,'dist')); await fs.writeFile(path.join(r.root,'dist','bundle.js'),'generated'); await fs.writeFile(path.join(r.root,'.env'),'TOKEN=private'); const b = await r.capture(scope); expect(b.input_hash).toBe(a.input_hash); expect(b.files.some(f => f.relative_path === '.env')).toBe(false); expect(JSON.stringify(b)).not.toContain('private'); expect(b.exclusions.some(x => x.relative_path === '.env')).toBe(true); });
  it('blocks oversized files, LFS pointers and unresolved generated inputs', async () => { const r = await setup(); await fs.writeFile(path.join(r.root,'large'),'12345'); expect((await r.capture({max_file_bytes:4})).completeness).toBe('INCOMPLETE'); await fs.writeFile(path.join(r.root,'large'),'version https://git-lfs.github.com/spec/v1\noid sha256:'+'a'.repeat(64)+'\nsize 123\n'); expect((await r.capture()).diagnostics.some(x => x.includes('LFS'))).toBe(true); expect((await r.capture({unresolved_inputs:['codegen source']})).completeness).not.toBe('COMPLETE'); });
  it('blocks submodules and out-of-root directory links', async () => { const r = await setup(); await r.git('update-index','--add','--cacheinfo',`160000,${await r.git('rev-parse','HEAD')},sub`); expect((await r.capture()).diagnostics.some(x => x.includes('SUBMODULE'))).toBe(true); await fs.symlink(path.dirname(r.root),path.join(r.root,'escape'),'junction'); const m = await r.capture(); expect(m.completeness).toBe('INCOMPLETE'); expect(m.diagnostics).toContain('UNSAFE_OR_UNREADABLE_INPUT: escape'); });
  it('keeps documentation as input unless explicitly excluded', async () => { const r = await setup(); const a = await r.capture(); await fs.writeFile(path.join(r.root,'README.md'),'new docs'); expect((await r.capture()).input_hash).not.toBe(a.input_hash); });
  it('respects nested ignore rules during safe directory enumeration', async () => { const r = await setup(); await fs.mkdir(path.join(r.root,'new')); await fs.writeFile(path.join(r.root,'new','.gitignore'),'ignored.txt\n'); await fs.writeFile(path.join(r.root,'new','ignored.txt'),'not input'); await fs.writeFile(path.join(r.root,'new','source.ts'),'input'); const m = await r.capture(); expect(m.files.some(f => f.relative_path === 'new/source.ts')).toBe(true); expect(m.files.some(f => f.relative_path === 'new/ignored.txt')).toBe(false); });
  it('does not run configured external diff or text conversion commands', async () => { const r = await setup(); const marker = path.join(r.root,'ran'); const command = `echo unsafe > '${marker.replaceAll('\\','/')}'`; await r.git('config','diff.external',command); await r.git('config','diff.unsafe.textconv',command); await fs.writeFile(path.join(r.root,'.gitattributes'),'*.txt diff=unsafe\n'); await fs.writeFile(path.join(r.root,'source.txt'),'changed'); expect((await r.capture()).completeness).toBe('COMPLETE'); await expect(fs.stat(marker)).rejects.toMatchObject({code:'ENOENT'}); });
  it('keeps task payload changes but excludes only StackGate state artifacts', async () => { const r = await setup(); await fs.mkdir(path.join(r.root,'.stackgate','tasks'),{recursive:true}); await fs.mkdir(path.join(r.root,'.stackgate','state')); const task = path.join(r.root,'.stackgate','tasks','task.yaml'); await fs.writeFile(task,'revision: 1'); const a = await r.capture(); await fs.writeFile(path.join(r.root,'.stackgate','state','artifact.json'),'generated'); expect((await r.capture()).input_hash).toBe(a.input_hash); await fs.writeFile(task,'revision: 2'); expect((await r.capture()).input_hash).not.toBe(a.input_hash); });
  it('detects index entries whose object is missing', async () => { const r = await setup(); await r.git('update-index','--add','--cacheinfo',`100644,${'1'.repeat(40)},missing.txt`); const m = await r.capture(); expect(m.completeness).toBe('INCOMPLETE'); expect(m.diagnostics).toContain('MISSING_OBJECT: missing.txt'); });
  it('hashes binary and CRLF bytes without normalizing them', async () => { const r = await setup(); const bytes = Buffer.from([0,255,13,10,32]); await fs.writeFile(path.join(r.root,'binary.dat'),bytes); const m = await r.capture(); expect(m.files.find(f => f.relative_path === 'binary.dat')?.digest).toBe(hashBytes(bytes)); });
  it('does not execute configured clean filters while computing dirty changes', async () => { const r = await setup(); const marker = path.join(r.root,'filter-ran'); await r.git('config','filter.unsafe.clean',`echo unsafe > '${marker.replaceAll('\\','/')}'; cat`); await fs.writeFile(path.join(r.root,'.gitattributes'),'*.txt filter=unsafe\n'); await fs.writeFile(path.join(r.root,'source.txt'),'changed'); await r.capture(); await expect(fs.stat(marker)).rejects.toMatchObject({code:'ENOENT'}); });
  it('blocks CRLF LFS pointers and emulated symlink checkouts', async () => { const r = await setup(); await fs.writeFile(path.join(r.root,'pointer'),'version https://git-lfs.github.com/spec/v1\r\noid sha256:'+'a'.repeat(64)+'\r\nsize 123\r\n'); const pointer = await r.capture(); expect(pointer.diagnostics).toContain('LFS_OBJECT_UNAVAILABLE: pointer'); await fs.writeFile(path.join(r.root,'link'),'source.txt'); const oid = await r.git('hash-object','-w','--','link'); await r.git('update-index','--add','--cacheinfo',`120000,${oid},link`); expect((await r.capture()).diagnostics).toContain('SYMLINK_CHECKOUT_UNVERIFIED: link'); });
});
