export const hash = 'a'.repeat(64);
export const at = '2026-09-20T00:00:00Z';
export const checkFact = { check_id: 'unit', required: true, status: 'PASS', result_kind: 'junit', exit_code: 0, expected_test_ids: ['unit-001'], executed_test_ids: ['unit-001'], discovered_tests: 1, executed_tests: 1, skipped_tests: 0, flaky_tests: 0, reasons: [], evidence_refs: ['ev-unit-001'] };
export function protocolFixture(name: string): any {
  const check = { schema_version: '0.1', ...checkFact, run_id: 'run_fixture', step_id: 'step_unit', attempt_id: 'attempt_1', attempts: [{ attempt_id: 'attempt_1', started_at: at, finished_at: at, raw_exit_code: 0, status: 'PASS', evidence_refs: ['ev-unit-001'] }] };
  const artifact = { schema_version: '0.1', artifact_id: 'ev-unit-001', run_id: 'run_fixture', check_id: 'unit', attempt_id: 'attempt_1', relative_path: 'artifacts/checks/unit/attempt_1/junit.xml', artifact_kind: 'report', media_type: 'application/xml', size: 120, digest: hash, sensitivity: 'regular', redaction_state: 'REDACTED' };
  const gate = { schema_version: '0.1', verdict: 'PASS', freshness: 'FRESH', decision: 'ALLOW', exit_code: 0, reasons: [], run_id: 'run_fixture', policy_hash: hash, evaluated_at: at };
  const fixtures: Record<string, unknown> = {
    'check-result': check, artifact, 'gate-evaluation': gate,
    plan: { schema_version: '0.1', plan_id: 'plan_fixture', task_id: 'performance', task_revision: 1, profile: 'integration', input_hash: hash, policy_hash: hash, target_contract_hashes: { api: hash }, toolchain_hash: hash, environment_requirements_hash: hash, required_check_ids: ['unit'], steps: [{ step_id: 'step_unit', check_id: 'unit', adapter_id: 'junit', command_id: 'web_unit', depends_on: [], required: true, timeout_ms: 10000, resource_locks: [], expected_artifacts: ['junit.xml'], expected_test_ids: ['unit-001'], min_tests: 1, parameters: { adapter_id: 'junit', report_name: 'junit.xml' } }], plan_hash: hash },
    probe: { schema_version: '0.1', kind: 'stackgate-probe', run_id: 'run_fixture', check_id: 'runtime', attempt_id: 'attempt_1', instance_id: 'instance_fixture', operations: [{ operation_key: 'api:GET /api/performance', request_id: 'request_fixture', status_code: 200, media_type: 'application/json', schema_valid: true, response_body: { data: { performance: { total_return: 0.1234 } } }, assertions: [{ assertion_id: 'total-return-is-number', passed: true }], backend_observation_ref: 'backend-requests.jsonl#request_fixture' }], completed: true },
    event: { schema_version: '0.1', event_id: 'event_fixture', run_id: 'run_fixture', seq: 1, at, type: 'check.finished', payload: { payload_version: '0.1', check_result: check } },
    'input-manifest': { schema_version: '0.1', repo_id: 'repo_fixture', worktree_id: 'worktree_fixture', platform_id: 'win32-x64', base_oid: 'b'.repeat(40), head_oid: 'c'.repeat(40), target_tip_oid: 'b'.repeat(40), git_object_format: 'sha1', files: [{ relative_path: 'src/main.ts', kind: 'file', digest: hash, mode: '100644', tracked: true, staged: false, unstaged: true }], exclusions: [], staged_changes: [], unstaged_changes: ['src/main.ts'], completeness: 'COMPLETE', diagnostics: [], input_hash: hash },
    environment: { schema_version: '0.1', run_id: 'run_fixture', mode: 'attach', status: 'READY', frontend_origin: 'http://127.0.0.1:5173', backend_origin: 'http://127.0.0.1:8000', instance_id: 'instance_fixture', provenance: 'OBSERVED', input_hash: hash, image_ids: [], resources: [], data_revision: 'fixture-1', observations: ['ev-startup'], reasons: [] },
    finding: { schema_version: '0.1', finding_id: 'finding_fixture', rule_id: 'SG-CONTRACT-TYPE_MISMATCH', category: 'contract', severity: 'error', message: 'Expected number', observed_facts: { actual_type: 'string' }, suggested_cause: 'Candidate response drift', recommended_action: 'Match confirmed target', locations: [{ source: 'candidate', relative_path: 'candidate-openapi.json', pointer: '/paths' }], evidence_refs: ['ev-unit-001'] },
    'playwright-report': { schema_version: '0.1', kind: 'stackgate-playwright', run_id: 'run_fixture', check_id: 'e2e', attempt_id: 'attempt_1', started_at: at, ended_at: at, completed: true, status: 'passed', inventory: [{ test_id: 'performance-summary', title: 'shows total return', file: 'tests/acceptance/performance.spec.ts', line: 1, annotations: [{ type: 'stackgate-id', description: 'performance-summary' }], only: false }], attempts: [{ test_id: 'performance-summary', retry: 0, expected_status: 'passed', actual_status: 'passed', duration_ms: 10, attachments: [], errors: [] }], requests: [{ test_id: 'performance-summary', request_id: 'request_fixture', instance_id: 'instance_fixture', operation_key: 'api:GET /api/performance', url: 'http://127.0.0.1:8000/api/performance', status_code: 200, backend_observation_ref: 'backend-requests.jsonl#request_fixture' }], console: [] },
    run: { schema_version: '0.1', run_id: 'run_fixture', plan_id: 'plan_fixture', phase: 'COMPLETED', verdict: 'PASS', created_at: at, started_at: at, finished_at: at, task_id: 'performance', task_revision: 1, repo_id: 'repo_fixture', worktree_id: 'worktree_fixture', base_oid: 'b'.repeat(40), git_object_format: 'sha1', input_hash: hash, plan_hash: hash, policy_hash: hash, target_contract_hashes: { api: hash }, tool_versions: { node: '24.11.1' }, environment_ref: 'environment.json', data_revision: 'fixture-1', checks: [check], artifact_refs: ['ev-unit-001'], coverage_gaps: [], canceled: false }
  };
  if (!(name in fixtures)) throw new Error('Unknown test fixture: ' + name);
  return structuredClone(fixtures[name]);
}
