import {readFileSync,writeFileSync,readdirSync,existsSync} from 'node:fs';
const [id,status,next,...files]=process.argv.slice(2);
const filename='docs/implementation/audit-fixes.json';
const ledger=JSON.parse(readFileSync(filename,'utf8'));
const task=ledger.tasks.find(t=>t.task_id===id);
if(!task||!['IN_PROGRESS','IMPLEMENTED_UNVERIFIED','DONE','BLOCKED'].includes(status)||!next)throw Error('Invalid audit update');
const records=readdirSync('docs/implementation/evidence').filter(f=>f.startsWith(id.toLowerCase()+'-')&&f.endsWith('.json')).map(f=>JSON.parse(readFileSync('docs/implementation/evidence/'+f,'utf8')));
task.verification=[...new Map([...task.verification,...records].map(r=>[r.evidence_path,r])).values()].sort((a,b)=>a.started_at.localeCompare(b.started_at));
task.actual_files=[...new Set([...task.actual_files,...files])];
for(const file of task.actual_files)if(!existsSync(file))throw Error('Missing actual file '+file);
if(status==='DONE'&&(!task.verification.some(r=>r.exit_code===0)||!task.actual_files.length||!task.dependencies.every(d=>ledger.tasks.find(t=>t.task_id===d)?.status==='DONE')))throw Error('Missing evidence/files/dependencies');
task.status=status;task.next_action=next;
writeFileSync(filename,JSON.stringify(ledger,null,2)+'\n');
const original='docs/implementation/tasks.json',tasks=JSON.parse(readFileSync(original,'utf8'));
tasks.audit_fixes={ledger:filename,baseline_commit:ledger.baseline_commit,current:id,status};
writeFileSync(original,JSON.stringify(tasks,null,2)+'\n');
const done=tasks.tasks.filter(t=>t.status==='DONE').map(t=>t.task_id);
writeFileSync('docs/implementation/PROGRESS.md',`# StackGate implementation progress\n\n当前：${id} ${status}。M1-R 修复验收完成后进入 M2。\n\n历史完成：${done.join(', ')}。历史任务记录保持原状。\n\n审计修复完成：${ledger.tasks.filter(t=>t.status==='DONE').map(t=>t.task_id).join(', ')}。\n\n下一步：${next}\n\n## 最近真实验证\n\n${task.verification.slice(-6).map(r=>'- `'+r.command+'` → '+r.exit_code+'；[证据]('+r.evidence_path.replace('docs/implementation/','')+')').join('\n')}\n\n## 续接\n\n- [审计修复账本](audit-fixes.json)；[M1-R00 基线](audit-m1-r00.md)；[原任务账本](tasks.json)。\n- HEAD 基线 ${ledger.baseline_commit}；当前修复未提交，未推送或部署。\n- 失败反例与中间失败保留；未执行的平台和检查不视为通过。\n`);
console.log(id+': '+status);
