import { describe,expect,it } from 'vitest';
import { loadContract } from '../../../packages/adapter-oasdiff/src/load-contract.js';
import { validatePayload } from '../../../packages/adapter-oasdiff/src/runtime-validator.js';
function document(schema:unknown):any{return {openapi:'3.1.1',info:{title:'fixture',version:'1'},paths:{'/value':{post:{requestBody:{required:true,content:{'application/json':{schema}}},responses:{'200':{description:'ok',content:{'application/json':{schema}}}}}}}};}
function load(schema:unknown){return loadContract(Buffer.from(JSON.stringify(document(schema))),'runtime-target');}
function validate(schema:unknown,payload:unknown,direction:'request'|'response'='response'){return validatePayload({contract:load(schema),operation_key:'POST /value',direction,status_code:200,media_type:'application/json',payload});}
describe('strict directional payload schemas',()=>{
  it('rejects number strings without converting or mutating input',()=>{const payload={value:'12'};const before=structuredClone(payload);const result=validate({type:'object',properties:{value:{type:'number'}},required:['value']},payload);expect(result.status).toBe('FAIL');expect(result.supported).toBe(true);expect(result.violations.some(v=>v.pointer==='/value'&&v.keyword==='type')).toBe(true);expect(payload).toEqual(before);});
  it('reports escaped JSON pointers for missing required properties',()=>{const result=validate({type:'object',properties:{'a/b~c':{type:'string'}},required:['a/b~c']},{});expect(result.status).toBe('FAIL');expect(result.violations.some(v=>v.pointer==='/a~1b~0c'&&v.keyword==='required')).toBe(true);});
  it.each([
    [{type:'number'},12,'PASS'],[{type:'integer'},1.5,'FAIL'],[{type:'boolean'},true,'PASS'],[{type:'string'},null,'FAIL'],
    [{type:['string','null']},null,'PASS'],[{type:'string',enum:['a','b']},'c','FAIL'],
    [{type:'array',items:{type:'number'}},[1,2],'PASS'],[{type:'array',items:{type:'number'}},[1,'2'],'FAIL'],
    [{anyOf:[{type:'number'},{type:'null'}]},null,'PASS'],[{anyOf:[{type:'number'},{type:'null'}]},'2','FAIL'],
  ])('validates declared supported shape %#',(schema,payload,status)=>expect(validate(schema,payload).status).toBe(status));
  it('preserves disallowed additional properties and rejects them',()=>{const payload={value:1,extra:'retained'};const result=validate({type:'object',properties:{value:{type:'number'}},additionalProperties:false},payload);expect(result.status).toBe('FAIL');expect(payload.extra).toBe('retained');expect(result.violations.some(v=>v.pointer==='/extra')).toBe(true);expect(validate({type:'object',properties:{value:{type:'number'}},additionalProperties:true},payload).status).toBe('PASS');});
  it('applies required readOnly/writeOnly semantics in opposite directions',()=>{const schema={type:'object',properties:{id:{type:'string',readOnly:true},password:{type:'string',writeOnly:true}},required:['id','password'],additionalProperties:false};expect(validate(schema,{password:'synthetic'},'request').status).toBe('PASS');expect(validate(schema,{id:'id'},'response').status).toBe('PASS');expect(validate(schema,{},'response').violations.some(v=>v.pointer==='/id')).toBe(true);expect(validate(schema,{},'request').violations.some(v=>v.pointer==='/password')).toBe(true);});
  it('resolves directional annotations through local property refs',()=>{const doc=document({type:'object',properties:{id:{$ref:'#/components/schemas/Id'}},required:['id']});doc.components={schemas:{Id:{type:'string',readOnly:true}}};const contract=loadContract(Buffer.from(JSON.stringify(doc)),'refs');const request={contract,operation_key:'POST /value',media_type:'application/json',payload:{}};expect(validatePayload({...request,direction:'request'}).status).toBe('PASS');expect(validatePayload({...request,direction:'response',status_code:200}).status).toBe('FAIL');});
  it('selects exact, class and default status schema in precedence order',()=>{const doc=document({type:'number'});doc.paths['/value'].post.responses['2XX']={description:'class',content:{'application/json':{schema:{type:'string'}}}};doc.paths['/value'].post.responses.default={description:'fallback',content:{'application/json':{schema:{type:'boolean'}}}};const contract=loadContract(Buffer.from(JSON.stringify(doc)),'statuses');for(const [status_code,payload]of [[200,1],[201,'created'],[404,false]] as const)expect(validatePayload({contract,operation_key:'POST /value',direction:'response',status_code,media_type:'application/json; charset=utf-8',payload}).status).toBe('PASS');});
  it('fails an undeclared status or media type and an unknown operation',()=>{const contract=load({type:'number'});const input={contract,operation_key:'POST /value',direction:'response' as const,status_code:404,media_type:'application/json',payload:1};expect(validatePayload(input).status).toBe('FAIL');expect(validatePayload({...input,status_code:200,media_type:'text/plain'}).status).toBe('FAIL');expect(validatePayload({...input,operation_key:'GET /missing'}).status).toBe('INCOMPLETE');});
  it.each([{type:'string',format:'uuid'},{type:'number',default:1},{type:'number',minimum:0},{oneOf:[{type:'string'},{type:'number'}]}])('keeps unsupported semantics incomplete rather than coercing to any',schema=>{const result=validate(schema,{});expect(result.status).toBe('INCOMPLETE');expect(result.supported).toBe(false);expect(result.diagnostics.length).toBeGreaterThan(0);});
  it('does not accept a changed document with the old raw identity',()=>{const contract=load({type:'number'});(contract.document as any).paths['/value'].post.responses['200'].content['application/json'].schema={type:'string'};expect(validatePayload({contract,operation_key:'POST /value',direction:'response',status_code:200,media_type:'application/json',payload:'wrong'}).status).toBe('INCOMPLETE');});
  it('does not execute payload accessors and does not return payload values in violations',()=>{let calls=0;const payload=Object.defineProperty({},'value',{enumerable:true,get(){calls++;return 'secret';}});const result=validate({type:'object',properties:{value:{type:'number'}}},payload);expect(result.status).toBe('INCOMPLETE');expect(calls).toBe(0);expect(JSON.stringify(result)).not.toContain('secret');});
});
