import {it,expect} from 'vitest';
import {validateSchema} from '../../../packages/contracts/src/index.js';
import type {RunnerResult} from '../../../packages/core/src/ports/runner.js';
import {validateCommandProvenance} from '../../../packages/core/src/services/command-provenance.js';
const expected={command_id:'unit',authorization_hash:'a'.repeat(64),executable_digest:'b'.repeat(64),platform_id:'win32-x64'};
const observed=():RunnerResult=>({status:'EXITED',raw_exit_code:0,signal:null,process:{pid:42,creation_identity:'123456',owner_token:'owned-token'},artifacts:[],diagnostics:[],execution:{command_id:'unit',authorization_hash:expected.authorization_hash,command_hash:'c'.repeat(64),executable_digest:expected.executable_digest},provenance:{mechanism:'WINDOWS_JOB_OBJECT',broker_version:'1',cleanup:'VERIFIED'}});
it('accepts a fully bound observed command and nonzero business exit',()=>{const result=observed();expect(validateCommandProvenance(result,expected)).toEqual([]);result.raw_exit_code=7;expect(validateCommandProvenance(result,expected)).toEqual([]);});
it.each(['execution','process','provenance','mechanism','cleanup','broker','authorization','command','executable','command-hash'])('rejects missing or forged %s evidence',kind=>{const result=observed();if(kind==='execution')delete result.execution;if(kind==='process')result.process=null;if(kind==='provenance')delete result.provenance;if(kind==='mechanism')result.provenance!.mechanism='CLIENT_ASSERTED';if(kind==='cleanup')result.provenance!.cleanup='UNVERIFIED';if(kind==='broker')delete result.provenance!.broker_version;if(kind==='authorization')result.execution!.authorization_hash='d'.repeat(64);if(kind==='command')result.execution!.command_id='other';if(kind==='executable')result.execution!.executable_digest='d'.repeat(64);if(kind==='command-hash')result.execution!.command_hash='';if(kind!=='command-hash')expect(validateSchema('command-execution',{schema_version:'0.1',kind:'stackgate-command-execution',run_id:'run_test',check_id:'unit',step_id:'unit',attempt_id:'attempt_one',command_id:'unit',started_at:'2026-09-20T00:00:00.000Z',finished_at:'2026-09-20T00:00:01.000Z',result}).ok).toBe(true);expect(validateCommandProvenance(result,expected).length).toBeGreaterThan(0);});
it.each(['ERROR','TIMED_OUT','CANCELED'] as const)('retains ordinary %s failure evidence without inventing process completion',status=>{const result=observed();result.status=status;result.process=null;delete result.execution;delete result.provenance;expect(validateCommandProvenance(result,expected)).toEqual([]);});
