import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { describe,expect,it } from 'vitest';
import type { TaskPayload,ConfirmationRecord } from '../../../packages/contracts/src/index.js';
import { loadContract } from '../../../packages/adapter-oasdiff/src/load-contract.js';
import { OasdiffAdapter } from '../../../packages/adapter-oasdiff/src/tool.js';
import { ContractService } from '../../../packages/core/src/services/contract-service.js';
import { hashBytes } from '../../../packages/core/src/storage/hash.js';
import { canonicalJson } from '../../../packages/core/src/storage/canonical-json.js';
const identity={executable:resolve('tools/bin/oasdiff-1.32.1/oasdiff.exe'),expected_sha256:'sha256:cce550834cddfa7584a5cfde8deb2a6a57effcbc445f040f4f7ac37da47e8173',expected_version:'1.32.1',trusted:true};
const fixture=async(name:string)=>loadContract(await readFile(`tests/fixtures/contracts/${name}.json`),name);
const service=()=>new ContractService(new OasdiffAdapter(identity));
const payload=async():Promise<TaskPayload>=>JSON.parse(await readFile('tests/fixtures/tasks/draft.json','utf8'));
function confirmation(task:TaskPayload,target:string):ConfirmationRecord{return {schema_version:'0.1',task_id:task.task_id,revision:task.revision,payload_hash:hashBytes(Buffer.from(canonicalJson(task))),target_hashes:{api:target.replace(/^sha256:/,'')},protected_input_hash:'e'.repeat(64),confirmed_at:'2026-09-20T00:00:00.000Z',confirmation_source:'local-review'};}
describe('real three-way contract orchestration',()=>{
  it('uses real compatibility while missing candidate/runtime remain NOT_EXECUTED',async()=>{const baseline=await fixture('target'),target=await fixture('candidate-correct');const report=await service().compareThreeWay({baseline,target,candidate:null,task:null,policy:{service_id:'api',require_confirmation:true}});expect(report.compatibility.status).toBe('PASS');expect(report.compatibility.evidence.length).toBeGreaterThan(0);expect(report.implementation_alignment.status).toBe('NOT_EXECUTED');expect(report.runtime_validation.status).toBe('NOT_EXECUTED');expect(report.target_authorization).toBe('UNCONFIRMED');expect(report.source_hashes.target).toBe(target.raw_hash);});
  it('rejects absent target behavior independently of mutual breaking checks',async()=>{const base=await fixture('target');const doc=structuredClone(base.document!);const schema=(((doc.paths as any)['/api/performance'].get.responses['200'].content['application/json']).schema);schema.properties.newOptional={type:'string'};const target=loadContract(Buffer.from(JSON.stringify(doc)),'extra-target');const tool=new OasdiffAdapter(identity);expect((await tool.breaking(base,target)).status).toBe('PASS');expect((await tool.breaking(target,base)).status).toBe('PASS');const report=await new ContractService(tool).compareThreeWay({baseline:base,target,candidate:base,task:null,policy:{service_id:'api'}});expect(report.implementation_alignment.status).toBe('FAIL');expect(report.runtime_validation.status).toBe('NOT_EXECUTED');});
  it('requires real confirmation hashes and grants no approval to a draft',async()=>{const baseline=await fixture('upgrade-baseline'),target=await fixture('upgrade-target'),task=await payload();task.compatibility={mode:'approved-changes',approved_breaking_rules:[{operation_key:'api:GET /api/performance',rule_id:'SG-CONTRACT-REQUIRED_PROPERTY_REMOVED',baseline_hash:baseline.raw_hash.slice(7),target_hash:target.raw_hash.slice(7),reason:'reviewed upgrade'}]};const request={baseline,target,candidate:target,task:{payload:task,confirmation:confirmation(task,target.raw_hash)},policy:{service_id:'api',require_confirmation:true}};const approved=await service().compareThreeWay(request);expect(approved.compatibility.status).toBe('PASS');expect(approved.compatibility.findings.every(f=>f.approved)).toBe(true);const draft=await service().compareThreeWay({...request,task:{payload:task,confirmation:null}});expect(draft.compatibility.status).toBe('FAIL');});
  it('blocks target byte drift despite equal behavior and separates export errors',async()=>{const baseline=await fixture('target'),task=await payload(),target=loadContract(Buffer.concat([await readFile('tests/fixtures/contracts/target.json'),Buffer.from('\n')]),'changed-target');const report=await service().compareThreeWay({baseline,target,candidate:baseline,task:{payload:task,confirmation:confirmation(task,baseline.raw_hash)},policy:{service_id:'api',require_confirmation:true}});expect(report.target_authorization).toBe('CHANGED');expect(report.implementation_alignment.status).toBe('BLOCKED');const failed=await service().compareThreeWay({baseline,target:baseline,candidate:null,candidate_error:'export failed',task:null,policy:{service_id:'api'}});expect(failed.implementation_alignment.status).toBe('ERROR');});
  it('blocks unsupported target schema before projection rather than silently aligning it',async()=>{const target=loadContract(Buffer.from(JSON.stringify({openapi:'3.1.1',info:{title:'x',version:'1'},paths:{'/x':{get:{responses:{'200':{description:'ok',content:{'application/json':{schema:{type:'string',format:'mystery'}}}}}}}}})),'unknown-format');const report=await service().compareThreeWay({baseline:target,target,candidate:target,task:null,policy:{service_id:'api'}});expect(report.compatibility.status).toBe('BLOCKED');expect(report.implementation_alignment.status).toBe('BLOCKED');expect(report.runtime_validation.status).toBe('NOT_EXECUTED');});
  it.each(['external','missing','malformed'])('preserves %s loader diagnostics before attempting a tool',async(kind)=>{const baseline=await fixture('target');const document=structuredClone(baseline.document!);document.components={schemas:{Unsafe:{$ref:kind==='external'?'https://example.invalid/private':'#/components/schemas/Missing'}}};const target=loadContract(Buffer.from(kind==='malformed'?'{':JSON.stringify(document)),'invalid-target');let calls=0;const guarded=new ContractService({async breaking(){calls++;throw new Error('Tool must not run');}});const report=await guarded.compareThreeWay({baseline,target,candidate:null,task:null,policy:{service_id:'api'}});expect(calls).toBe(0);expect(report.compatibility.status).toBe('BLOCKED');expect(report.compatibility.diagnostics).toEqual(target.diagnostics);});
});
